# Writes a header defining NETNATSUE_BUILD_DATE (YYYY-MM-DD, UTC).
# Run at build time via cmake -P; copy_if_different keeps the header
# untouched (and dependents unrebuilt) unless the date changed.
string(TIMESTAMP NETNATSUE_BUILD_DATE "%Y-%m-%d" UTC)
file(WRITE "${OUT}.tmp"
	"// Generated by cmake/BuildDate.cmake - do not edit\n"
	"#define NETNATSUE_BUILD_DATE \"${NETNATSUE_BUILD_DATE}\"\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
	"${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
